export default {
	type: "object",
	properties: {
		erfNumber: { type: "string" },
		erfSize: { type: "number" },
		officeNumber: { type: "string" },
		officeEmail: { type: "string" },
		fax: { type: "string" },
		accountNumber: { type: "string" },
		currentBalance: { type: "number" },
		isOverdue: { type: "boolean" },
		managementCompany: { type: "string" },
		propertyId: { type: "string" },
		tradingAs: { type: "string" },
		vat: { type: "string" },
		mdaAccNumber: { type: "string" },
		municipalValue: { type: "string" },
		notes: { type: "string" },
		allocatedUserId: { type: "string" },
		approached: { type: "string" },
	},
	required: ["erfNumber", "currentBalance"],
} as const;
