export default {
	type: "object",
	properties: {
		name: { type: "string" },
		coordinates: { type: "string" },
		postalAddress: { type: "string" },
		streetNumber: { type: "number" },
		streetName: { type: "string" },
		address2: { type: "string" },
		city: { type: "string" },
		province: { type: "string" },
		postalCode: { type: "string" },
		country: { type: "string" },
	},
	required: [
		"name",
		"coordinates",
		"postalAddress",
		"streetNumber",
		"streetName",
		"city",
		"province",
		"postalCode",
		"country"],
} as const;
